---
- hosts: network
  become: yes
  pre_tasks:
    # To prevent trying this demo on unsupported version, define the minimum Cumulus Linux
    # Release supported by this demo.
    - name: Verify Minimum Software Version
      assert:
        that: "{{ansible_lsb.release is version_compare('3.5', '>=') }}"
        msg: >
          "Cumulus Linux version must be 3.5 or later.
          Version {{ansible_lsb.release}} detected"
  roles:
    - interface_configuration
    - routing_configuration
    - ntp_in_mgmt_vrf

- hosts: fabric_netqagent
  become: yes
  roles:
    - fabric_netqagent_configure

- hosts: servers
  user: cumulus
  become: yes
  become_method: sudo
  roles:
    - server_interface_configuration
    
